version: '3'
services:

  postgres-vector:
    image: ankane/pgvector:v0.5.1
    container_name: linkedagent-postgres
    environment:
      POSTGRES_USER: linkedagent
      POSTGRES_PASSWORD: password
      POSTGRES_DB: linkedagent
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: linkedagent-redis
    ports:
      - "6379:6379"
