spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/auth/**, /api/agent/**
        - id: system-management
          uri: lb://system-management
          predicates:
            - Path=/api/sys/**
        - id: ai-rag-service
          uri: lb://ai-rag-service
          predicates:
            - Path=/api/ai/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml

server:
  port: 8080
